config/routes.rb
Rails.application.routes.draw do

  #mise en place du root principal
  root to:'pages#home' 

  #mise en place d'une page team depuis le controller pages
  get '/team', to: 'pages#team', as: 'team' #création d'un nom pour le chemin

  #mise en place d'une page contact depuis le controller pages
  get '/contact', to: 'pages#contact', as: 'contact' #création d'un nom pour le chemin

  #mise en place d'une route dynamique
  get 'welcome(/:first_name)', to: 'pages#welcome', as: 'welcome' #création d'un nom pour le chemin
  #mise en place d'un parametre optionnel pour first_name

  #mise en place d'un route dynamique
  get 'potin/:id', to:'pages#potin', as: 'potin'

  #mise en place d'un route dynamique
  get 'potin/auteur/:title', to:'pages#auteur', as: 'auteur'

end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :affiliations
  has_many :tags, through: :affiliations
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :affiliations
  has_many :gossips, through: :affiliations
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

#définition de la page home
  def home
    puts params.inspect
    @gossips = Gossip.all
  end

#définition de la page team
  def team
    
  end

#définition de la page contact
  def contact
    
  end

#définition de la page welcome dynamique
  def welcome
    @first_name = params[:first_name]
    puts params[:first_name].inspect
  end

#définition de la page potin dynamique
  def potin
    @gossips = Gossip.all
    @id = params[:id]
  end


#définition de la page auteur dynamique
def auteur
  @gossips = Gossip.all
  @title = params[:title]
end  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Intégration du CSS Bootstrap aux views -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Intégration du Javascript Boostrap aux views -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="<%= root_path %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <span class="fs-4" style="color:#8064A2; font-weight: 900">The Gossip Project</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="<%= root_path %>" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="<%= team_path %>" class="nav-link">Team</a></li>
        <li class="nav-item"><a href="<%= contact_path %>" class="nav-link">Contact</a></li>
        <li class="nav-item"><a href="<%= welcome_path %>" class="nav-link">Welcome</a></li>

      </ul>
    </header>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  
    <div class="container text-center">
      <hr>
      <p style="color:#8064A2">Create with ❤️ by <a href="https://twitter.com/guillaume_rygn" style="text-decoration:underline; color:#8064A2">Guillaume Reygner</a></p>
    </div>

  </body>
</html>

app/views/pages/auteur.html.erb
<div class="container" style="height:80vh">
  <h1>Voici la page de l'auteur : <span style="color:#8064A2"><%= @title%></span> </h1>
  <h3 class="mb-5">Ses articles :</h3>

  <div class="container row justify-content-center">
    <% @gossips.each do |gossip| %>
      <% if gossip.title == @title%>
        <div class="card mb-3 mx-4 card-home" style="width: 18rem;">
          <div class="card-body">
            <p class="card-text"><em><%= gossip.content %></em></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <a href="<%= root_path %>" class="btn btn-primary mt-3 rounded-pill">👈 Revenir au menu</a>
</div>

app/views/pages/contact.html.erb
<!-- View HTML de notre page Contact-->


<div class="container contact " style="height:80vh">
	<div class="row">
		<div class="col-md-3">
			<div class="contact-info">
				<img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
				<h2>Contactez nous</h2>
				<h4>Nous avons hâte de vous lire !</h4>
			</div>
		</div>
		<div class="col-md-9">
			<div class="contact-form">
				<div class="form-group">
				  <label class="control-label col-sm-2" for="fname">Prénom :</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="fname" placeholder="Enter First Name" name="fname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="lname">Nom:</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="lname" placeholder="Enter Last Name" name="lname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="email">Email:</label>
				  <div class="col-sm-10">
					<input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="comment">Commentaire:</label>
				  <div class="col-sm-10">
					<textarea class="form-control" rows="5" id="comment"></textarea>
				  </div>
				</div>
				<div class="form-group">        
				  <div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-default">Envoyer</button>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<h1 class="row justify-content-center mb-5"> Bienvenue sur The Gossip Project</h1>
<p class="row justify-content-center mb-5" style="color:#C7C7F1"> Parcours le mur des gossips pour voir les dernières nouveautés</p>


<div class="container row justify-content-center">
<% @gossips.each do |gossip| %>

<div class="card mb-3 mx-4 card-home" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= gossip.title %></h5>
    <p class="card-text"><em><%= gossip.content %></em></p>
    <a href="potin/<%=gossip.id%>" class="btn btn-primary">Voir le potin</a>
  </div>
</div>
  <% end %>
</div>

app/views/pages/potin.html.erb
<div class="container" style="height:80vh">
    <% @gossips.each do |gossip| %>
      <% if gossip.id == @id.to_i%>
        <h3> <%= gossip.title %></h3>
        <p> <em><%= gossip.content %></em></p>
        <a href="<%= root_path %>" class="btn btn-primary m-3 rounded-pill">👈 Revenir au menu</a>
        <a href="auteur/<%= gossip.title%>" class=" btn-auteur btn btn-primary m-3 rounded-pill">Profil de l'auteur</a>
        <hr>
      <% end %>
    <% end %>
</div>

app/views/pages/team.html.erb
<!-- View HTML de notre page Team-->

<div class="py-5 team4">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <div class="col-md-7 text-center">
        <h1 class="mb-3">Une équipe incroyable</h1>
        <h6 class="subtitle">Avec un sens du détail incomparable de quoi faire palir les plus grand journalistes de notre époque</h6>
      </div>
    </div>
    <div class="row justify-content-center">
      <!-- column  -->
      <div class="col-lg-3 mb-4">
        <!-- Row -->
        <div class="row">
          <div class="col-md-12">
            <img src="https://avatars.githubusercontent.com/u/74305277?v=4" alt="wrapkit" class="img-fluid rounded-circle" />
          </div>
          <div class="col-md-12 text-center">
            <div class="pt-2">
              <h5 class="mt-4 font-weight-medium mb-0">Guillaume Reygner</h5>
              <h6 class="subtitle mb-3">Développeur depuis 1 mois</h6>
              <p>Si tu lis ces lignes c'est que tu as franchement le goût du détail</p>
              <ul class="list-inline">
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Row -->
      </div>
      <div class="col-lg-1 mb-4">
      </div>
      <!-- column  -->
      <!-- column  -->
      <div class="col-lg-3 mb-4">
        <!-- Row -->
        <div class="row justify-content-center">
          <div class="col-md-12">
            <img src="https://avatars.githubusercontent.com/u/86610960?v=4" alt="wrapkit" class="img-fluid rounded-circle bastien" />
          </div>
          <div class="col-md-12 text-center">
            <div class="pt-2">
              <h5 class="mt-4 font-weight-medium mb-0">Bastien Arlot</h5>
              <h6 class="subtitle mb-3">Digital nomade</h6>
              <p>Il n'est pas présent et a fait le projet de son côté car il est a Venise le bougre</p>
              <ul class="list-inline">
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#" class="text-decoration-none d-block px-1"><i class="icon-social-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Row -->
      </div>
      
        <!-- Row -->
      </div>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="container text-center" style="height:80vh">



<div class="card mb-3 mx-4 rounded-pill" >
  <div class="card-body">
    <h5 class="card-title">
      <h1>Bienvenue <span style="color:#8064A2"><%= @first_name %></span>
        <% if @first_name != nil%>
          ! </br></br><h3>🎉 Bien joué tu as trouvé une fonction secrète 😎</h3>
        <%end%></h1>
    </h5>
  </div>
</div>


</br>
<h3>⚠️ Dans l'URL rajoute à la fin un "/nomquetuveux" une surprise t'attend</h3>
</div>